<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__ .'/tests')
    ->in(__DIR__ .'/src');

return (new PhpCsFixer\Config())
    ->setRules([
        'align_multiline_comment' => true,
        'array_indentation' => true,
        'array_syntax' => ['syntax' => 'short'],
        'blank_line_after_namespace' => true,
        'blank_line_after_opening_tag' => true,
        'blank_line_before_statement' => [ 'statements' => [ 'return' ] ],
        'braces' => [ 'allow_single_line_closure' => true ],
        'cast_spaces' => true,
        'class_attributes_separation' => [ 'elements' =>
            [
                'const' => 'none',
                'method' => 'one',
                'property' => 'none',
                'trait_import' => 'none',
            ]
        ],
        'class_definition' => [ 'single_line' => true ],
        'concat_space' => ['spacing' => 'none'],
        'constant_case' => [ 'case' => 'lower' ],
        'declare_equal_normalize' => true,
        'declare_strict_types' => true,
        'elseif' => true,
        'encoding' => true,
        'full_opening_tag' => true,
        'function_declaration' => [ 'closure_function_spacing' => 'one' ],
        'function_typehint_space' => true,
        'include' => true,
        'indentation_type' => true,
        'linebreak_after_opening_tag' => true,
        'lowercase_cast' => true,
        'lowercase_keywords' => true,
        'lowercase_static_reference' => true,
        'magic_constant_casing' => true,
        'magic_method_casing' => true,
        'method_argument_space' => [ 'on_multiline' => 'ensure_fully_multiline'],
        'method_chaining_indentation' => true,
        'native_function_casing' => true,
        'native_function_type_declaration_casing' => true,
        'new_with_braces' => true,
        'normalize_index_brace' => true,
        'no_alternative_syntax' => true,
        'no_blank_lines_after_class_opening' => true,
        'no_closing_tag'=> true,
        'no_empty_comment' => true,
        'no_empty_statement' => true,
        'no_extra_blank_lines' => true,
        'no_leading_namespace_whitespace' => true,
        'no_mixed_echo_print' => [ 'use' => 'echo' ],
        'no_multiline_whitespace_around_double_arrow' => true,
        'multiline_whitespace_before_semicolons' => [ 'strategy' => 'no_multi_line' ],
        'no_superfluous_elseif' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'no_short_bool_cast' => true,
        'echo_tag_syntax' => [ 'format' => 'long' ],
        'no_spaces_after_function_name' => true,
        'no_spaces_around_offset' => [ 'positions' => ['inside', 'outside'] ],
        'no_spaces_inside_parenthesis' => true,
        'no_trailing_comma_in_list_call' => true,
        'no_trailing_comma_in_singleline_array' => true,
        'no_trailing_whitespace' => true,
        'no_trailing_whitespace_in_comment' => true,
        'no_unneeded_control_parentheses' => true,
        'no_unneeded_curly_braces' => [ 'namespaces' => false ],
        'no_unused_imports' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'no_whitespace_before_comma_in_array' => true,
        'no_whitespace_in_blank_line' => true,
        'object_operator_without_whitespace' => true,
        'ordered_imports' => true,
        'return_assignment' => true,
        'return_type_declaration' => [ 'space_before' => 'one' ],
        'semicolon_after_instruction' => true,
        'short_scalar_cast' => true,
        'simplified_null_return' => true,
        'single_blank_line_at_eof' => true,
        'single_blank_line_before_namespace' => true,
        'single_class_element_per_statement' => true,
        'single_import_per_statement' => true,
        'single_line_comment_style' => true,
        'single_line_after_imports' => true,
        'single_line_throw' => true,
        'single_quote' => [ 'strings_containing_single_quote_chars' => true ],
        'single_trait_insert_per_statement' => true,
        'space_after_semicolon' => true,
        'standardize_not_equals' => true,
        'switch_case_semicolon_to_colon' => true,
        'switch_case_space' => true,
        'ternary_operator_spaces' => true,
        'trailing_comma_in_multiline' => [ 'elements' => ['arrays'] ],
        'trim_array_spaces' => true,
        'unary_operator_spaces' => true,
        'visibility_required' => true,
        'whitespace_after_comma_in_array' => true,
        'yoda_style' => ['equal' => false, 'identical' => false, 'less_and_greater' => false],

        # Risky
        'global_namespace_import' => true,
        'increment_style' => ['style' => 'post'],
        'no_leading_import_slash' => true,
        'no_null_property_initialization' => true,
        'standardize_increment' => true,
        'ternary_to_null_coalescing' => true,

        # PHPDocs
        'no_blank_lines_after_phpdoc' => true,
        'no_empty_phpdoc' => true,
        'no_superfluous_phpdoc_tags' => [ 'allow_mixed' => false, 'allow_unused_params' => false, 'remove_inheritdoc' => false],
        'phpdoc_align' => false,
        'general_phpdoc_tag_rename' => true,
        'phpdoc_inline_tag_normalizer' => true,
        'phpdoc_tag_type' => true,
        'phpdoc_no_access' => true,
        'phpdoc_no_alias_tag' => true,
        'phpdoc_no_package' => true,
        'phpdoc_no_useless_inheritdoc' => true,
        'phpdoc_order' => true,
        'phpdoc_var_without_name' => true,

        # Declared Risky
        'modernize_types_casting' => true,

        # PhpUnit
        'php_unit_construct' => true,
        'php_unit_method_casing' => [ 'case' => 'camel_case' ],

        # Risky
        'php_unit_test_annotation' => true,
    ])
    ->setFinder($finder)
    ->setUsingCache(true)
    ->setRiskyAllowed(true);
