#!/bin/sh

FILES=$(git diff --name-only --cached --diff-filter=ACMR | grep '\.php$')

for file in $FILES
do
    php -l ${file} > /dev/null
    if [ $? -ne 0 ]; then
        echo "Aborting commit due to files with syntax errors" >&2
        exit 1
    fi
done

$(pwd)/vendor/bin/phpcs --standard=phpcs.xml -n $FILES  > /dev/null
if [ $? -ne 0 ]; then
    echo "Aborting commit due to code standard errors" >&2
    exit 1
fi
