version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@1.1.2
  aws-cli: circleci/aws-cli@0.1.6
  eks: tiendanube/eks@1.1.0
  slack: circleci/slack@1.0.0
  new-relic: tiendanube/new-relic@volatile
  docker: circleci/docker-publish@0.1.4

executors:
  default:
    machine:
      docker_layer_caching: true

jobs:

  style:
    executor: default
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Check Code Style
          command: |
            docker-compose -f docker-compose.cli.yml run --rm php-cs-fixer fix --verbose --show-progress=estimating \
            --dry-run --stop-on-violation

  test:
    executor: default
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Run PHPUnit Tests
          command: |
            docker-compose -f docker-compose.yml run --rm php-cli vendor/bin/phpunit

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - style:
          context: microservices
      - test:
          context: microservices
          requires:
            - style